minimumReleaseAge: 4320

overrides:
  "swiper": "^12.1.2"
  "uuid": "^11.1.1"

allowBuilds:
  esbuild: true

registries:
  https://artifactory.ci.csc.fi/artifactory/api/npm/sds-npm/:
    scopes: ["@"]
    prefix: npmjs
  https://artifactory.ci.csc.fi/artifactory/api/npm/sds-npm-jsr-remote/:
    scopes: ["@jsr"]
  https://artifactory.ci.csc.fi/artifactory/api/npm/sds-npm-github-remote/:
    prefix: gh
