stages:
  - deps
  - lint
  - test
  - build
  - release

variables:
  DEV_IMAGE: $ARTIFACTORY_SERVER/sds/sdd-golang-common-ci
  BUILDER_IMAGE: $ARTIFACTORY_SERVER/sds/sdd-ubuntu-golang-builder-ci
  GOCACHE: $CI_PROJECT_DIR/.go-build

include:
  - project: 'sds-dev/releases'
    ref: main
    file: 'releases.yml'

default:
  image: $DEV_IMAGE
  tags:
    - docker-exec

install-deps:
  stage: deps
  rules:
    - when: always
  script:
    - pnpm install --dir frontend
    - pnpm run --dir frontend build
    - go mod tidy && go mod vendor
  cache:
    - &global_pnpm_cache
      key:
        files:
          - frontend/pnpm-lock.yaml
      paths:
        - frontend/node_modules/
    - &global_go_cache
      key: $CI_COMMIT_REF_SLUG
      paths:
        - vendor/
        - frontend/dist/

backend-lint:
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
  cache:
    <<: *global_go_cache
    policy: pull
  script:
    - golangci-lint run -v ./... --allow-parallel-runners --timeout 10m --output.code-climate.path stdout | tee gl-code-quality-report.json
    - go fmt ./...
    - go vet -tags=fuse3 ./...
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths:
      - gl-code-quality-report.json

frontend-lint:
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
  cache:
    <<: *global_pnpm_cache
    policy: pull
  script:
    - pnpm run --dir frontend lint

jfrog-go-audit:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
  tags:
    - sds
  script:
    # Update upstream package checksums in case they have changed
    - go mod vendor
    # Configure JFrog Artifactory repositories
    - jf config import "${JF_CONFIG}"
    - jf go-config --repo-resolve $ARTIFACTORY_SERVER
    # Audit Go project
    - jf audit --go --licenses --extended-table --min-severity=Medium

test:
  image:
    name: $DEV_IMAGE
    docker:
      user: 1000:1000
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
  cache:
    <<: *global_go_cache
    policy: pull
  before_script:
    - go install gotest.tools/gotestsum@v1.13.0
    - go install github.com/boumenot/gocover-cobertura@v1.4.0
  script:
    - packages=$(go list -buildvcs=false ./... | grep -v -e frontend -e test -e build -e certs)
    - >
      gotestsum --junitfile report.xml --format testname --rerun-fails --rerun-fails-abort-on-data-race --packages "${packages}"
      --
      -race -tags=fuse3 -coverprofile=coverage.out -covermode=atomic ${packages}
    - gocover-cobertura < coverage.out > coverage.xml
    - go tool cover -func coverage.out
  coverage: '/total:\s+\(statements\)\s+(\d+\.\d+)%/'
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml


build-dev:
  stage: build
  image: $BUILDER_IMAGE
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
      allow_failure: true
  variables:
    SECURE_FILES_DOWNLOAD_PATH: './certs'
  cache:
    - <<: *global_pnpm_cache
      policy: pull
    - <<: *global_go_cache
      policy: pull
  before_script:
    - jf config import "${JF_CONFIG}"
    - go install github.com/wailsapp/wails/v2/cmd/wails@v2.11.0
  script:
    - curl -sSf https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
    - |
      go build -ldflags '-w -s' -o data-gateway-cli-amd64-0000.0.0 ./cmd/cli
      jf s --licenses data-gateway-cli-amd64-0000.0.0 --repo-path ${ARTIFACTORY_SERVER_DESKTOP_BINARY_REPO}
      jf rt u data-gateway-cli-amd64-0000.0.0 $ARTIFACTORY_SERVER_DESKTOP_BINARY_REPO/$CI_PROJECT_NAME/data-gateway-cli-amd64-0000.0.0
    - |
      cd cmd/gui
      /usr/local/go/bin/wails build -clean -upx -trimpath -s -tags webkit2_41 -ldflags "-X sda-filesystem/internal/api.Version=0000.0.0"
      cd ../..
      mv build/bin/data-gateway data-gateway-gui-amd64-0000.0.0
      jf s --licenses data-gateway-gui-amd64-0000.0.0 --repo-path ${ARTIFACTORY_SERVER_DESKTOP_BINARY_REPO}
      jf rt u data-gateway-gui-amd64-0000.0.0 $ARTIFACTORY_SERVER_DESKTOP_BINARY_REPO/$CI_PROJECT_NAME/data-gateway-gui-amd64-0000.0.0

build-artifacts:
  stage: build
  image: $BUILDER_IMAGE
  rules :
    - if: '$CI_COMMIT_TAG !~ "/^$/"'
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
  services:
    - docker:dind
  variables:
    SECURE_FILES_DOWNLOAD_PATH: './certs'
  cache:
    - <<: *global_pnpm_cache
      policy: pull
    - <<: *global_go_cache
      policy: pull
  before_script:
    - jf config import "${JF_CONFIG}"
  script:
    - curl -sSf https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
    - |
      go build -ldflags '-w -s' -o data-gateway-cli-amd64-${CI_COMMIT_TAG} ./cmd/cli
      jf s --licenses data-gateway-cli-amd64-${CI_COMMIT_TAG} --repo-path ${ARTIFACTORY_SERVER_BINARY_REPO}
      jf rt u data-gateway-cli-amd64-${CI_COMMIT_TAG} $ARTIFACTORY_SERVER_BINARY_REPO/$CI_PROJECT_NAME/data-gateway-cli-amd64-${CI_COMMIT_TAG}
      jf rt cp $ARTIFACTORY_SERVER_BINARY_REPO/$CI_PROJECT_NAME/data-gateway-cli-amd64-${CI_COMMIT_TAG} $ARTIFACTORY_SERVER_DESKTOP_BINARY_REPO/
    - |
      go build -ldflags '-w -s -X sda-filesystem/internal/api.Port=8283' -o data-gateway-cli-22-amd64-${CI_COMMIT_TAG} ./cmd/cli
      jf s --licenses data-gateway-cli-22-amd64-${CI_COMMIT_TAG} --repo-path ${ARTIFACTORY_SERVER_BINARY_REPO}
      jf rt u data-gateway-cli-22-amd64-${CI_COMMIT_TAG} $ARTIFACTORY_SERVER_BINARY_REPO/$CI_PROJECT_NAME/data-gateway-cli-22-amd64-${CI_COMMIT_TAG}
      jf rt cp $ARTIFACTORY_SERVER_BINARY_REPO/$CI_PROJECT_NAME/data-gateway-cli-22-amd64-${CI_COMMIT_TAG} $ARTIFACTORY_SERVER_DESKTOP_BINARY_REPO/
    - |
      go install github.com/wailsapp/wails/v2/cmd/wails@v2.11.0
      /usr/local/go/bin/wails doctor
    - |
      cd cmd/gui
      /usr/local/go/bin/wails build -clean -upx -trimpath -s -tags webkit2_41 -ldflags "-X sda-filesystem/internal/api.Version=${CI_COMMIT_TAG}"
      cd ../..
      mv build/bin/data-gateway data-gateway-gui-amd64-${CI_COMMIT_TAG}
      jf s --licenses data-gateway-gui-amd64-${CI_COMMIT_TAG} --repo-path ${ARTIFACTORY_SERVER_BINARY_REPO}
      jf rt u data-gateway-gui-amd64-${CI_COMMIT_TAG} $ARTIFACTORY_SERVER_BINARY_REPO/$CI_PROJECT_NAME/data-gateway-gui-amd64-${CI_COMMIT_TAG}
      jf rt cp $ARTIFACTORY_SERVER_BINARY_REPO/$CI_PROJECT_NAME/data-gateway-gui-amd64-${CI_COMMIT_TAG} $ARTIFACTORY_SERVER_DESKTOP_BINARY_REPO/
    - |
      cd cmd/gui
      /usr/local/go/bin/wails build -clean -upx -trimpath -s -ldflags "-X sda-filesystem/internal/api.Port=8283 -X sda-filesystem/internal/api.Version=${CI_COMMIT_TAG}"
      cd ../..
      mv build/bin/data-gateway data-gateway-gui-22-amd64-${CI_COMMIT_TAG}
      jf s --licenses data-gateway-gui-22-amd64-${CI_COMMIT_TAG} --repo-path ${ARTIFACTORY_SERVER_BINARY_REPO}
      jf rt u data-gateway-gui-22-amd64-${CI_COMMIT_TAG} $ARTIFACTORY_SERVER_BINARY_REPO/$CI_PROJECT_NAME/data-gateway-gui-22-amd64-${CI_COMMIT_TAG}
      jf rt cp $ARTIFACTORY_SERVER_BINARY_REPO/$CI_PROJECT_NAME/data-gateway-gui-22-amd64-${CI_COMMIT_TAG} $ARTIFACTORY_SERVER_DESKTOP_BINARY_REPO/

release:
  extends: .automated-release

  release:
    description: $(cat release_changes.md)
    assets:
      links:
        - name: data-gateway-cli-amd64-${RELEASE_VERSION} (artifactory)
          url: https://$ARTIFACTORY_SERVER/artifactory/$ARTIFACTORY_SERVER_BINARY_REPO/$CI_PROJECT_NAME/data-gateway-cli-amd64-${RELEASE_VERSION}
        - name: data-gateway-gui-amd64-${RELEASE_VERSION} (artifactory)
          url: https://$ARTIFACTORY_SERVER/artifactory/$ARTIFACTORY_SERVER_BINARY_REPO/$CI_PROJECT_NAME/data-gateway-gui-amd64-${RELEASE_VERSION}
        - name: data-gateway-gui-22-amd64-${RELEASE_VERSION} (artifactory)
          url: https://$ARTIFACTORY_SERVER/artifactory/$ARTIFACTORY_SERVER_BINARY_REPO/$CI_PROJECT_NAME/data-gateway-gui-22-amd64-${RELEASE_VERSION}

# This is a manual dry-run for developers to run in the merge request
update-versions-dryrun:
  extends: .update-versions-dryrun
  variables:
    UPDATE_VERSION_FILES_LIST: "cmd/gui/wails.json;frontend/package.json"

# This job updates the versions
update-versions:
  extends: .update-versions
  variables:
    UPDATE_VERSION_FILES_LIST: "cmd/gui/wails.json;frontend/package.json"
