stages:
  - lint
  - test
  - build
  - scan
  - push
  - release

include:
  - project: 'sds-dev/releases'
    ref: main
    file: 'releases.yml'
  - project: 'sds-dev/devops/renovate-runner'
    ref: main
    file: 'templates/renovate-config-validator.gitlab-ci.yml'

default:
  image: "${ARTIFACTORY_SERVER}/sds/sdd-common-ci:2026.9.3@sha256:f4e479e35c1155e8422bec6d23315f5e6fae997188c6d41076600a6804ab9089"
  retry: 2
  interruptible: true


########
# LINT #
########

backend-lint:
  stage: lint
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  tags:
    - sds-test
  before_script:
    - mkdir frontend/dist && touch frontend/dist/empty.txt
  script:
    - golangci-lint run -v ./... --allow-parallel-runners --timeout 10m --output.code-climate.path stdout | tee gl-code-quality-report.json
    - go fmt ./...
    - go vet -tags=fuse3 ./...
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths:
      - gl-code-quality-report.json

frontend-lint:
  stage: lint
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  tags:
    - sds-test
  script:
    - pnpm run --dir frontend lint

pylint:
  stage: lint
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  tags:
    - sds-test
  script:
    - pylint --disable import-error,duplicate-code,line-too-long **/*.py

black:
  stage: lint
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  tags:
    - sds-test
  script:
    - black --line-length=100 --check --verbose -- .

shellcheck:
  stage: lint
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  tags:
    - sds-test
  script:
    - git ls-files -z -- '*.sh' | xargs -0 -r shellcheck

renovate-config-validator:
  stage: lint
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'


########
# TEST #
########

test:
  image:
    name: "${ARTIFACTORY_SERVER}/sds/sdd-common-ci:2026.9.3@sha256:f4e479e35c1155e8422bec6d23315f5e6fae997188c6d41076600a6804ab9089"
    docker:
      user: 1000:1000
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
  tags:
    - sds-test
  before_script:
    - mkdir frontend/dist && touch frontend/dist/empty.txt
    - go install gotest.tools/gotestsum@v1.13.0
    - go install github.com/boumenot/gocover-cobertura@v1.4.0
  script:
    - packages=$(go list -buildvcs=false ./... | grep -v -e frontend -e test -e build -e certs)
    - >
      gotestsum --junitfile report.xml --format testname --rerun-fails --rerun-fails-abort-on-data-race --packages "${packages}"
      --
      -race -tags=fuse3 -coverprofile=coverage.out -covermode=atomic ${packages}
    - gocover-cobertura < coverage.out > coverage.xml
    - go tool cover -func coverage.out
  coverage: '/total:\s+\(statements\)\s+(\d+\.\d+)%/'
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml


#########
# BUILD #
#########

.build-artifacts:
  stage: build
  image: "${ARTIFACTORY_SERVER}/sds/sdd-ubuntu-golang-builder-ci:2026.9.3@sha256:e809dac25274bdea6b9bf0dbe0ef2a09ed73c63a95248919dd855c52f734110b"
  rules :
    - if: $CI_COMMIT_TAG
      interruptible: false
      variables:
        VERSION: $CI_COMMIT_TAG
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        VERSION: 0000.0.0
  tags:
    - sds-build
  variables:
    SECURE_FILES_DOWNLOAD_PATH: './certs'
  artifacts:
    when: on_success
    expire_in: 1 hour
    paths:
      - data-gateway-*

build-cli-artifacts:
  extends: .build-artifacts
  before_script:
    - curl -sSf https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
    - jf config import "${JF_CONFIG_READ_ONLY}"
  script:
    - go build -ldflags "-w -s ${EXTRA_LDFLAGS}" -o "data-gateway-${BINARY_TYPE}-${VERSION}" ./cmd/cli
  parallel:
    matrix:
      - BINARY_TYPE: cli-amd64
        EXTRA_LDFLAGS: ""
      - BINARY_TYPE: cli-22-amd64
        EXTRA_LDFLAGS: "-X sda-filesystem/internal/api.Port=8283"

build-gui-artifacts:
  extends: .build-artifacts
  before_script:
    - curl -sSf https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
    - pnpm config list
    - pnpm install --dir frontend
    - pnpm run --dir frontend build
    - go install github.com/wailsapp/wails/v2/cmd/wails@v2.15.0
    - wails doctor
    - jf config import "${JF_CONFIG_READ_ONLY}"
  script:
    - cd cmd/gui
    - >
      wails build
      -clean -upx -trimpath -s ${EXTRA_WAILS_ARGS}
      -ldflags "-X sda-filesystem/internal/api.Version=${VERSION} ${EXTRA_LDFLAGS}"
    - cd ../..
    - mv build/bin/data-gateway "data-gateway-${BINARY_TYPE}-${VERSION}"
  parallel:
    matrix:
      - BINARY_TYPE: gui-amd64
        EXTRA_WAILS_ARGS: ""
        EXTRA_LDFLAGS: ""
      - BINARY_TYPE: gui-22-amd64
        EXTRA_WAILS_ARGS: "-tags webkit2_41"
        EXTRA_LDFLAGS: "-X sda-filesystem/internal/api.Port=8283"


########
# SCAN #
########

scan-artifacts:
  stage: scan
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $GITLAB_USER_NAME != "renovate-bot"'
      variables:
        WATCH: sds-watch
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $GITLAB_USER_NAME == "renovate-bot"'
      variables:
        WATCH: sds-renovate
  tags:
    - sds-test
  variables:
    VERSION: 0000.0.0
  before_script:
    - jf config import "${JF_CONFIG_READ_ONLY}"
  script:
    - jf scan --extended-table --watches=$WATCH "data-gateway-${BINARY_TYPE}-${VERSION}"
  parallel:
    matrix:
      - BINARY_TYPE: ["cli-amd64", "cli-22-amd64", "gui-amd64", "gui-22-amd64"]


########
# PUSH #
########

push-dev:
  stage: push
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
      allow_failure: true
  tags:
    - sds-upload
  before_script:
    - jf config import "${JF_CONFIG}"
  script:
    - >
      jf rt u data-gateway-${BINARY_TYPE}-amd64-0000.0.0
      $ARTIFACTORY_BINARY_REPO_DESKTOP/$CI_PROJECT_NAME/data-gateway-${BINARY_TYPE}-amd64-0000.0.0
  parallel:
    matrix:
      - BINARY_TYPE: ["cli", "gui"]

push-artifacts:
  stage: push
  rules:
    - if: $CI_COMMIT_TAG
      interruptible: false
  tags:
    - sds-upload
  variables:
    JFROG_CLI_BUILD_PROJECT: sds
  before_script:
    - jf config import "${JF_CONFIG}"
  script: |
      jf rt u "data-gateway-${BINARY_TYPE}-${CI_COMMIT_TAG}" \
      --build-name="data-gateway-${BINARY_TYPE}" --build-number="$CI_COMMIT_TAG" \
      "${ARTIFACTORY_BINARY_REPO}/${CI_PROJECT_NAME}/data-gateway-${BINARY_TYPE}-${CI_COMMIT_TAG}"

      jf rt build-publish "data-gateway-${BINARY_TYPE}" "$CI_COMMIT_TAG"

      jf rt cp "${ARTIFACTORY_BINARY_REPO}/${CI_PROJECT_NAME}/data-gateway-${BINARY_TYPE}-${CI_COMMIT_TAG}" \
      "${ARTIFACTORY_BINARY_REPO_DESKTOP}/"
  parallel:
    matrix:
      - BINARY_TYPE: ["cli-amd64", "cli-22-amd64", "gui-amd64", "gui-22-amd64"]


###########
# RELEASE #
###########

release:
  extends: .automated-release
  release:
    description: $(cat release_changes.md)
    assets:
      links:
        - name: data-gateway-cli-amd64-${RELEASE_VERSION} (artifactory)
          url: $ARTIFACTORY_URL/artifactory/$ARTIFACTORY_BINARY_REPO/$CI_PROJECT_NAME/data-gateway-cli-amd64-${RELEASE_VERSION}
        - name: data-gateway-cli-22-amd64-${RELEASE_VERSION} (artifactory)
          url: $ARTIFACTORY_URL/artifactory/$ARTIFACTORY_BINARY_REPO/$CI_PROJECT_NAME/data-gateway-cli-22-amd64-${RELEASE_VERSION}
        - name: data-gateway-gui-amd64-${RELEASE_VERSION} (artifactory)
          url: $ARTIFACTORY_URL/artifactory/$ARTIFACTORY_BINARY_REPO/$CI_PROJECT_NAME/data-gateway-gui-amd64-${RELEASE_VERSION}
        - name: data-gateway-gui-22-amd64-${RELEASE_VERSION} (artifactory)
          url: $ARTIFACTORY_URL/artifactory/$ARTIFACTORY_BINARY_REPO/$CI_PROJECT_NAME/data-gateway-gui-22-amd64-${RELEASE_VERSION}

# This is a manual dry-run for developers to run in the merge request
update-versions-dryrun:
  extends: .update-versions-dryrun
  variables:
    UPDATE_VERSION_FILES_LIST: "cmd/gui/wails.json;frontend/package.json"

# This job updates the versions
update-versions:
  extends: .update-versions
  variables:
    UPDATE_VERSION_FILES_LIST: "cmd/gui/wails.json;frontend/package.json"
