# Redis configuration file.

bind 0.0.0.0

# Explicitly disable all persistence
appendonly no
save ""

# Disable forced ACL based auth.
protected-mode no

# Require the client to issue an AUTH request before accessing the database
# using the following password
requirepass password2

port 6379

# evict the least recently used key
maxmemory-policy allkeys-lru

maxmemory 5M
