// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {airlock} from '../models';

export function ChangeMountPoint():Promise<string>;

export function CheckBucketExistence(arg1:string):Promise<boolean>;

export function CheckObjectExistences(arg1:airlock.UploadSet):Promise<Array<boolean>>;

export function ExportFiles(arg1:airlock.UploadSet,arg2:boolean):Promise<void>;

export function FilesOpen():Promise<boolean>;

export function GetDefaultMountPoint():Promise<string>;

export function GetUsername():Promise<string>;

export function InitFuse():Promise<void>;

export function InitializeAPI():Promise<boolean>;

export function OpenFuse():Promise<void>;

export function Panic():Promise<void>;

export function Quit():Promise<void>;

export function RefreshFuse():Promise<void>;

export function SelectFiles():Promise<Array<string>>;

export function WalkDirs(arg1:Array<string>,arg2:Array<string>,arg3:string):Promise<airlock.UploadSet>;
