// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeMountPoint() {
  return window['go']['main']['App']['ChangeMountPoint']();
}

export function CheckBucketExistence(arg1) {
  return window['go']['main']['App']['CheckBucketExistence'](arg1);
}

export function CheckObjectExistences(arg1) {
  return window['go']['main']['App']['CheckObjectExistences'](arg1);
}

export function ExportFiles(arg1, arg2) {
  return window['go']['main']['App']['ExportFiles'](arg1, arg2);
}

export function FilesOpen() {
  return window['go']['main']['App']['FilesOpen']();
}

export function GetDefaultMountPoint() {
  return window['go']['main']['App']['GetDefaultMountPoint']();
}

export function GetUsername() {
  return window['go']['main']['App']['GetUsername']();
}

export function InitFuse() {
  return window['go']['main']['App']['InitFuse']();
}

export function InitializeAPI() {
  return window['go']['main']['App']['InitializeAPI']();
}

export function OpenFuse() {
  return window['go']['main']['App']['OpenFuse']();
}

export function Panic() {
  return window['go']['main']['App']['Panic']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RefreshFuse() {
  return window['go']['main']['App']['RefreshFuse']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function WalkDirs(arg1, arg2, arg3) {
  return window['go']['main']['App']['WalkDirs'](arg1, arg2, arg3);
}
