// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Authenticate(arg1:string):Promise<void>;

export function ChangeMountPoint():Promise<string>;

export function CheckEncryption(arg1:string,arg2:string):Promise<any>;

export function ExportFile(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function FilesOpen():Promise<boolean>;

export function GetDefaultMountPoint():Promise<string>;

export function InitFuse():Promise<void>;

export function InitializeAPI():Promise<void>;

export function LoadFuse():Promise<void>;

export function Login(arg1:string,arg2:string):Promise<boolean>;

export function OpenFuse():Promise<void>;

export function Panic():Promise<void>;

export function Quit():Promise<void>;

export function RefreshFuse():Promise<void>;

export function SelectFile():Promise<string>;
