// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeMountPoint() {
  return window['go']['main']['App']['ChangeMountPoint']();
}

export function CheckEncryption(arg1, arg2) {
  return window['go']['main']['App']['CheckEncryption'](arg1, arg2);
}

export function ExportFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportFile'](arg1, arg2, arg3);
}

export function GetDefaultMountPoint() {
  return window['go']['main']['App']['GetDefaultMountPoint']();
}

export function InitializeAPI() {
  return window['go']['main']['App']['InitializeAPI']();
}

export function LoadFuse() {
  return window['go']['main']['App']['LoadFuse']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function OpenFuse() {
  return window['go']['main']['App']['OpenFuse']();
}

export function Panic() {
  return window['go']['main']['App']['Panic']();
}

export function RefreshFuse() {
  return window['go']['main']['App']['RefreshFuse']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
