// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function AddLog(arg1:string,arg2:Array<string>):Promise<void>;

export function SaveLogs(arg1:Array<main.Log>):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
