// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLog(arg1, arg2) {
  return window['go']['main']['LogHandler']['AddLog'](arg1, arg2);
}

export function SaveLogs() {
  return window['go']['main']['LogHandler']['SaveLogs']();
}

export function SetContext(arg1) {
  return window['go']['main']['LogHandler']['SetContext'](arg1);
}
