// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function AddLog(arg1:string,arg2:Array<string>):Promise<void>;

export function SaveLogs():Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
