// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteProjects() {
  return window['go']['main']['ProjectHandler']['DeleteProjects']();
}

export function SetContext(arg1) {
  return window['go']['main']['ProjectHandler']['SetContext'](arg1);
}
