// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {filesystem} from '../models';
import {context} from '../models';

export function AddProject(arg1:filesystem.Project):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
