name: Linting go code

on:
  push:

jobs:
  build:
    name: Check code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.24"]
        nodejs-version: ["24"]
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v5

      - name: Setup go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libgtk-3-dev libwebkit2gtk-4.1-dev npm pkg-config libfuse3-dev -y

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.nodejs-version }}
          cache: "pnpm"
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Build assets
        run: |
          pnpm install --dir frontend
          pnpm run --dir frontend build

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: latest
          args: --timeout=10m
          skip-cache: true
