name: Linting go code

on:
  push:

jobs:
  build:
    name: Check code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.22"]
        nodejs-version: ["20"]
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libgtk-3-dev libwebkit2gtk-4.0-dev npm pkg-config libfuse-dev -y

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodejs-version }}
          cache: "pnpm"
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Build assets
        run: |
          pnpm install --dir frontend
          pnpm run --dir frontend build

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6.1.0
        with:
          version: latest
          args: -E bodyclose,gocritic,gofmt,gosec,govet,nestif,nlreturn,revive,rowserrcheck --exclude G401,G501,G107,G602,G115 --timeout=10m
          skip-cache: true
